### ISSUE TITLE
Enable the Automatically scanning for vulnerabilities as error

### ISSUE THREAD

**Issue by skounis** [eu-digital-green-certificates/dgc-overview#65]
GitHub provides this service for free for open source repos
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors

## Tasks
- [ ] Check if we have it enabled 
- [ ] Enable it if it is not
- [ ] Share the reports with EC
